### PR TITLE
Create index.html

### PR DESCRIPTION
**Pull request by geekgeek**
The single html file riot tag compiler. The dependencies are the javascript file riot+compiler.js. It are using the riot.compile() function to compile riot tags.

### CODE REVIEW

**Comment by geekgeek** [comment]
Here is examples at plunker of the html riot online tag compiler:

Version with html and JavaScript
https://plnkr.co/edit/1ukKJeYxfcmeXf1VLY1f?p=preview
Version with html, JavaScript and Riot tags
https://plnkr.co/edit/mqQBuqoVNfitDqSxi1Ch?p=preview

**Comment by GianlucaGuarini** [comment]
thank you!

**Comment by geekgeek** [comment]
Thank you : ).

**Comment by geekgeek** [comment]
Here is a plunker version that are using the Ace editor and when you type on the left, it compiles automatically on the right for each change on the left. If you like this version, you can just use it.  ( it is w3c compliant with 0 errors and warnings).

Nice improvements on the index file btw : ).

Here is the link:

http://plnkr.co/edit/IkhpFo9tE3toAhG2vDkZ?p=preview

**Pull request merged**
